import "reflect-metadata";
import { DataSource } from "typeorm";

export const AppDataSource = new DataSource({
  type: "mysql",
  host: "localhost",
  port: 3306,
  username: "root",
  password: "",
  database: "afar-backend",
  synchronize: true,
  logging: false,
  entities: ["src/entity/*.ts"],
  // entities: //[__dirname + '/**/*.entity.{js,ts}']
  // [
  //   User,
  //   Contractor,
  //   ContractorApplication,
  //   ContractorCar,
  //   ContractorEmployee,
  //   ContractorProject,
  //   ContractorService,
  //   ContractorShareHolder,
  //   ContractionProperty,
  //   ConstructionLevel,
  //   AppliedFor,
  //   ContractionType,
  //   PropertyType,
  //   Competency,
  //   Consultant,
  //   ConsultantCar,
  //   ConsultantApplication,
  //   ConsultantEmployee,
  //   ConsultantProject,
  //   ConsultantService,
  //   ConsultantShareHolder,
  //   ConsultantContractionProperty,
  // ],
  migrations: [],
  subscribers: [],
});
